version: "3"

services:
  app:
    build:
      context:
    ports:
      - "8000:8000"
    volumes: 
      - ./app:./app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
# docker-compose build
# docker-compose run app sh -c "django-admin.py startproject app ."
# git add .
# git commit -a

# in vi - Setup docker and Django project.
# :wq